#!/bin/bash
#raiz="/home/solar/installProyect/raiz/"
raiz="/"

#borramos configuracion para lightdm
if [ -f "$raiz"usr/share/lightdm/lightdm.conf.d/01_debian.conf_bak ]
then
	rm "$raiz"usr/share/lightdm/lightdm.conf.d/01_debian.conf_bak
fi	

if [ -f "$raiz"usr/share/lightdm/lightdm-gtk-greeter.conf.d/01_debian.conf_bak ]
then
	rm "$raiz"usr/share/lightdm/lightdm-gtk-greeter.conf.d/01_debian.conf_bak
fi

#borramos session
if [ -d "$raiz"usr/share/xsessions_bak ]
then
	rm -rf "$raiz"usr/share/xsessions_bak
fi