#!/bin/bash
echo "PowerOff v0.1 - Tools Solar"

rcmSolar='{"message":{"call":"PowerOff"}}'	
rcmSend rcmPowerOff $rcmSolar
#echo $rcmSolar > ~/.containerrcm/.rcmPowerOff.rcmSolar
xdotool key Super+Tab
echo ""

			